solving: cycle call during return
      System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Privacies.User.Contacts.Host.Contacts.Host.Contacts.Host.Contacts.Host.Contacts.Host.Contacts.Host.Contacts.Host.Contacts.Host.Contacts.Host.Contacts.ContactId.